### ISSUE TITLE
[api-platform/core] InvalidConfigurationException when execute recipe

### ISSUE THREAD

**Issue by jdecool** [symfony/recipes#127]
When I try to install api-platform with Symfony Flex, an exception is throw.

Step to reproduce :
1. Create a new project using `composer create-project symfony/skeleton myapp`
2. Install API Platform using the api-platform/api-pack : `composer require api-platform/api-pack`

Output :

```bash
Using version ^2.1@dev for api-platform/api-pack
./composer.json has been updated
...
Writing lock file
Generating autoload files
Symfony operations: 7 recipes
  - Configuring symfony/translation (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/twig-bundle (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/security-bundle (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/console (3.3): From github.com/symfony/recipes:master
  - Configuring doctrine/doctrine-cache-bundle (1.3.0): From auto-generated recipe
  - Configuring doctrine/doctrine-bundle (1.6): From github.com/symfony/recipes:master
  - Configuring api-platform/core (2.1): From github.com/symfony/recipes:master
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  PHP Fatal error:  Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "loader_paths" under "api_platform" in /home/jeremy/Workspace/todolist/myapp/vendor/symfony/config/Definition/ArrayNode.php:317
!!  Stack trace:
!!  #0 /home/jeremy/Workspace/todolist/myapp/vendor/symfony/config/Definition/BaseNode.php(264): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
!!  #1 /home/jeremy/Workspace/todolist/myapp/vendor/symfony/config/Definition/Processor.php(33): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
!!  #2 /home/jeremy/Workspace/todolist/myapp/vendor/symfony/config/Definition/Processor.php(50): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array)
!!  #3 /home/jeremy/Workspace/todolist/myapp/vendor/symfony/dependency-injection/Extension/Extension.php(94): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(ApiPlatform\Core\Bridge\Symfony\Bundle\DependencyInjection\Configura in /home/jeremy/Workspace/todolist/myapp/vendor/symfony/config/Definition/ArrayNode.php on line 317
!!  
!!  Makefile:14: recipe for target 'cache-clear' failed
!!  
!!  make: *** [cache-clear] Error 255
!!  
!!  

Installation failed, reverting ./composer.json to its original content.

```

**Comment by xabbuh** [comment]
I would have expected this a non-issue with #126 being merged. Maybe that's a caching issue of the recipes server.

**Comment by fabpot** [comment]
There was a bug in the server cache management, which has been fixed now.

**Comment by jdecool** [comment]
Thanks
