### ISSUE TITLE
locale parameter defined under services

### ISSUE THREAD

**Issue by teohhanhui** [symfony/recipes#82]
```
# composer create-project "symfony/skeleton:^3.3"
 .
Installing symfony/skeleton (v3.3.0)
  - Installing symfony/skeleton (v3.3.0): Downloading (100%)         
Created project in .
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 22 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.1): Loading from cache
    Detected auto-configuration settings for "symfony/flex"
    Setting configuration and copying files
  - Installing symfony/stopwatch (v3.3.0): Loading from cache
  - Installing symfony/routing (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/routing"
  - Installing symfony/polyfill-mbstring (v1.3.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.0): Loading from cache
  - Installing symfony/http-foundation (v3.3.0): Loading from cache
  - Installing symfony/event-dispatcher (v3.3.0): Loading from cache
  - Installing symfony/http-kernel (v3.3.0): Loading from cache
  - Installing symfony/finder (v3.3.0): Loading from cache
  - Installing symfony/filesystem (v3.3.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v3.3.0): Loading from cache
  - Installing symfony/config (v3.3.0): Loading from cache
  - Installing symfony/class-loader (v3.3.0): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v3.3.0): Loading from cache
  - Installing doctrine/cache (v1.6.1): Loading from cache
  - Installing symfony/framework-bundle (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/framework-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
    Adding environment variable defaults
    Adding Makefile entries
    Adding entries to .gitignore
  - Installing symfony/yaml (v3.3.0): Loading from cache
  - Installing symfony/dotenv (v3.3.0): Loading from cache
Writing lock file
Generating autoload files
Executing script make cache-warmup [OK]
Skipping "assets:install --symlink --relative web" (needs symfony/console to run).

              
 What's next? 
              

  * Run your application:
    1. Change to the project directory
    2. Execute the make serve command;
    3. Browse to the http://localhost:8000/ URL.

  * Read the documentation at https://symfony.com/doc

# composer req console
Using version ^3.3 for symfony/console
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/console (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/console"
    Setting configuration and copying files
Writing lock file
Generating autoload files
Executing script make cache-warmup [OK]
Executing script assets:install --symlink --relative %WEB_DIR% [OK]

# composer req "api-platform/api-pack:^2.1@dev" "
api-platform/core:^2.1@dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 36 installs, 0 updates, 0 removals
  - Installing symfony/asset (v3.3.0): Loading from cache
  - Installing symfony/translation (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/translation"
    Setting configuration and copying files
    Setting parameters
  - Installing symfony/validator (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/validator"
  - Installing twig/twig (v2.3.2): Loading from cache
  - Installing symfony/twig-bridge (v3.3.0): Loading from cache
  - Installing symfony/twig-bundle (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/twig-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
  - Installing symfony/inflector (v3.3.0): Loading from cache
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing symfony/polyfill-php70 (v1.3.0): Loading from cache
  - Installing symfony/property-access (v3.3.0): Loading from cache
  - Installing symfony/polyfill-util (v1.3.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.3.0): Loading from cache
  - Installing symfony/security (v3.3.0): Loading from cache
  - Installing symfony/security-bundle (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/security-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
  - Installing symfony/expression-language (v3.3.0): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.2.1): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.1.1): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/collections (v1.4.0): Loading from cache
  - Installing doctrine/annotations (v1.4.0): Loading from cache
    Detected auto-configuration settings for "doctrine/annotations"
  - Installing doctrine/common (v2.7.2): Loading from cache
  - Installing symfony/doctrine-bridge (v3.3.0): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.3.0): Loading from cache
    Detected auto-configuration settings for "doctrine/doctrine-cache-bundle"
    Enabling the package as a Symfony bundle
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/dbal (v2.5.12): Loading from cache
  - Installing doctrine/doctrine-bundle (1.6.8): Loading from cache
    Detected auto-configuration settings for "doctrine/doctrine-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
    Adding environment variable defaults
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing doctrine/orm (v2.5.6): Loading from cache
  - Installing symfony/serializer (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/serializer"
  - Installing symfony/property-info (v3.3.0): Loading from cache
  - Installing willdurand/negotiation (v2.3.1): Loading from cache
  - Installing api-platform/core (dev-master 070278b): Loading from cache
    Detected auto-configuration settings for "api-platform/core"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
    Detected auto-configuration settings for "api-platform/api-pack"
Writing lock file
Generating autoload files
Executing script make cache-warmup [OK]
Executing script assets:install --symlink --relative %WEB_DIR% [KO]
 [KO]
Script assets:install --symlink --relative %WEB_DIR% returned with error code 255
!!  
!!  Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: A service definition must be an array or a string starting with "@" but string found for service "locale" in /srv/api-platform/etc/container.yaml. Check your YAML syntax. in /srv/api-platform/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:336
!!  Stack trace:
!!  #0 /srv/api-platform/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(228): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinition('locale', 'en', '/srv/api-platfo...', Array)
!!  #1 /srv/api-platform/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(140): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseDefinitions(Array, '/srv/api-platfo...')
!!  #2 /srv/api-platform/vendor/symfony/config/Loader/FileLoader.php(159): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/srv/api-platfo...', NULL)
!!  #3 /srv/api-platform in /srv/api-platform/vendor/symfony/config/Loader/FileLoader.php on line 174
!!  
!!  

Installation failed, reverting ./composer.json to its original content.
```

The contents of `etc/container.yaml` is:

```yaml
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    locale: 'en'
```

which is clearly wrong...

**Comment by teohhanhui** [comment]
I see this has already been fixed by symfony/flex#92.
